/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cams.cams.ServerFrames;

import com.cams.cams.CAMS_start_page_client;
import static com.cams.cams.ServerFrames.NewUser.domain;
import static com.cams.cams.ServerFrames.NewUser.port;
import static com.cams.cams.ServerFrames.NewUser.userDatabase;
import static com.cams.cams.ServerFrames.NewUser.userPassword;
import com.formdev.flatlaf.FlatDarculaLaf;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.UIManager;

/**
 *
 * @author hs475
 */
public class LabCreate extends javax.swing.JFrame {

    static String domain;
    static String port;
    static String stopMsg;
    static String userDatabase;
    static String userPassword;

    /**
     * Creates new form LabCreate
     */
    public LabCreate() {
        Properties prop = new Properties();
        try {
            prop.load(new FileInputStream("config.properties"));

            domain = prop.getProperty("domain");
            userDatabase = prop.getProperty("userDatabase");
            userPassword = prop.getProperty("userPassword");
            port = prop.getProperty("port");

        } catch (FileNotFoundException ex) {
            Logger.getLogger(CAMS_start_page_client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CAMS_start_page_client.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setIconImage(new ImageIcon(this.getClass().getResource("/Images/cams.png")).getImage());
        initStuff();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labTf = new javax.swing.JTextField();
        durationTf = new javax.swing.JTextField();
        deptBox = new javax.swing.JComboBox<>();
        degreeBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        submitLogin = new javax.swing.JButton();
        Date date= new Date();
        SpinnerDateModel sm =new SpinnerDateModel (date, null, null, Calendar.HOUR_OF_DAY);
        spinnerTime = new javax.swing.JSpinner(sm);
        jLabel7 = new javax.swing.JLabel();
        subjectBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insert new Lab information");

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/mac-mini.png"))); // NOI18N
        jLabel2.setText("Lab Number:");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/duration.png"))); // NOI18N
        jLabel3.setText("Lab Duration(minutes):");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/alarm-clock.png"))); // NOI18N
        jLabel4.setText("Start Time:");

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/alarm-clock.png"))); // NOI18N
        jLabel5.setText("Department:");

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/class.png"))); // NOI18N
        jLabel6.setText("Class Name:");

        labTf.setEditable(false);
        labTf.setBackground(new java.awt.Color(51, 51, 51));
        labTf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        labTf.setForeground(new java.awt.Color(255, 255, 255));

        durationTf.setBackground(new java.awt.Color(51, 51, 51));
        durationTf.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        durationTf.setForeground(new java.awt.Color(255, 255, 255));
        durationTf.setText("120");

        deptBox.setBackground(new java.awt.Color(51, 51, 51));
        deptBox.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        deptBox.setForeground(new java.awt.Color(204, 204, 204));
        deptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptBoxActionPerformed(evt);
            }
        });

        degreeBox.setBackground(new java.awt.Color(51, 51, 51));
        degreeBox.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        degreeBox.setForeground(new java.awt.Color(204, 204, 204));
        degreeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeBoxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submitLogin.setBackground(new java.awt.Color(102, 102, 102));
        submitLogin.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        submitLogin.setForeground(new java.awt.Color(255, 255, 255));
        submitLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/submit.png"))); // NOI18N
        submitLogin.setText("Submit");
        submitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLoginActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner. DateEditor (spinnerTime, "hh:mm:ss");
        spinnerTime.setEditor(de);
        spinnerTime.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        spinnerTime.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fourty/math-folder.png"))); // NOI18N
        jLabel7.setText("Subject Name:");

        subjectBox.setBackground(new java.awt.Color(51, 51, 51));
        subjectBox.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        subjectBox.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labTf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degreeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addComponent(subjectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(submitLogin)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(labTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(durationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinnerTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(degreeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(subjectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitLogin)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptBoxActionPerformed
        degreeBoxload();
        // TODO add your handling code here:
        //degreeBoxload();
    }//GEN-LAST:event_deptBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //initCombos();
        initStuff();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLoginActionPerformed
        try {
            // TODO add your handling code here:
            String labNumber = labTf.getText();
            String durationTime = durationTf.getText();
            String dept_name = deptBox.getSelectedItem().toString();
            //String degree_name=degreeBox.getSelectedItem().toString();
            String subject_name = subjectBox.getSelectedItem().toString();
            String class_name = degreeBox.getSelectedItem().toString();
            String starttime = spinnerTime.getValue().toString();
            //this is temporary fix
            String str = starttime;
            String[] arrOfStr = str.split(" ");
            String str2 = arrOfStr[3];
            //String[] arrOfStr2 = str2.split(":");
            //String laststr=""+arrOfStr2[0]+"/"+arrOfStr2[1]+"/"+arrOfStr2[2];
            //System.out.println(laststr);
            //this is temporary fix

            System.out.println(starttime);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://" + domain + ":" + port + "/cams", "" + userDatabase, "" + userPassword);
            Statement stmt = con.createStatement();
            System.out.println(starttime);

            stmt.executeUpdate("insert into `subjects` (`lab_number`, `start_time`, `total_time`, `dept_name`, `subject_name`, `class_name`) VALUES ('" + labNumber + "','" + str2 + "','" + durationTime + "','" + dept_name + "','" + subject_name + "','" + class_name + "')");

            JOptionPane.showMessageDialog(rootPane, "Subject Detail Added");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LabCreate.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Something went wrong ");
        } catch (SQLException ex) {
            Logger.getLogger(LabCreate.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Server error ");
        }

    }//GEN-LAST:event_submitLoginActionPerformed

    private void degreeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeBoxActionPerformed
        // TODO add your handling code here:
        subjectBoxload();
    }//GEN-LAST:event_degreeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> degreeBox;
    private javax.swing.JComboBox<String> deptBox;
    private javax.swing.JTextField durationTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField labTf;
    private javax.swing.JSpinner spinnerTime;
    private javax.swing.JComboBox<String> subjectBox;
    private javax.swing.JButton submitLogin;
    // End of variables declaration//GEN-END:variables

    private void initStuff() {

        loadLabNumber();
        loadDeptBox();
    }

    private void loadLabNumber() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://" + domain + ":" + port + "/cams", "" + userDatabase, "" + userPassword);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT lab_number FROM subjects ORDER BY lab_number DESC LIMIT 1");
            rs.next();
            int last_lab = Integer.parseInt(rs.getString("lab_number")) + 1;
            labTf.setText(last_lab + "");

        } catch (Exception ex) {
            Logger.getLogger(LabCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDeptBox() {
        try {
            deptBox.removeAllItems();
            degreeBox.removeAllItems();
            subjectBox.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://" + domain + ":" + port + "/cams", "" + userDatabase, "" + userPassword);
            Statement stmt = con.createStatement();
            ResultSet sn = stmt.executeQuery("select distinct dept_name from dept ");

            while (sn.next()) {
                deptBox.addItem(sn.getString("dept_name"));
            }
            degreeBoxload();
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane, "Server is not ON");
            System.out.println("unable to load1");
        }
    }

    private void degreeBoxload() {
        try {
            degreeBox.removeAllItems();
            subjectBox.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://" + domain + ":" + port + "/cams", "" + userDatabase, "" + userPassword);
            Statement stmt = con.createStatement();
            String dept_name = deptBox.getSelectedItem().toString();

            ResultSet sn = stmt.executeQuery("select distinct class_name from dept where dept_name='" + dept_name + "'");

            while (sn.next()) {
                degreeBox.addItem(sn.getString("class_name"));
            }
            subjectBoxload();
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane, "Server is not ON");
            System.out.println("unable to load1");
        }
    }

    private void subjectBoxload() {
        try {
            subjectBox.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://" + domain + ":" + port + "/cams", "" + userDatabase, "" + userPassword);
            Statement stmt = con.createStatement();
            String degree_box = degreeBox.getSelectedItem().toString();

            ResultSet sn = stmt.executeQuery("select distinct subject from dept where class_name='" + degree_box + "'");

            while (sn.next()) {
                subjectBox.addItem(sn.getString("subject"));
            }
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(rootPane, "Server is not ON");
            System.out.println("unable to load1");
        }
    }
}
